name: Deploy Website to S3 and CloudFront

on:
  push:
    branches:
      - main  # וודא שזה השם של ה-Branch שלך

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::996393379970:role/MichaelGitHubActionRole
          aws-region: eu-north-1

      - name: Deploy to S3
        run: aws s3 sync . s3://michael-website-aws --delete

      - name: Create CloudFront Invalidation
        # כאן הוספנו את הפקודה החדשה לפי עמוד 43 במצגת
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} \
            --paths "/*"